# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_gen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1312, 884)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #2E3440;  /* Dark Theme */\n"
"    color: #D8DEE9;\n"
"    font-size: 14px;\n"
"    font-family: \"Segoe UI\", \"Arial\", sans-serif;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pump_stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.pump_stacked_widget.setGeometry(QtCore.QRect(0, 0, 460, 440))
        self.pump_stacked_widget.setStyleSheet("/* QStackedWidget */\n"
"QStackedWidget {\n"
"    background-color: #2E3440;\n"
"    border: 2px solid #4C566A;\n"
"    border-radius: 6px;\n"
"    padding: 5px;\n"
"}")
        self.pump_stacked_widget.setFrameShape(QtWidgets.QFrame.Box)
        self.pump_stacked_widget.setObjectName("pump_stacked_widget")
        self.pump_coms = QtWidgets.QWidget()
        self.pump_coms.setObjectName("pump_coms")
        self.cnc_coms_list = QtWidgets.QComboBox(self.pump_coms)
        self.cnc_coms_list.setGeometry(QtCore.QRect(150, 130, 145, 35))
        self.cnc_coms_list.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.cnc_coms_list.setObjectName("cnc_coms_list")
        self.cnc_coms_refresh = QtWidgets.QPushButton(self.pump_coms)
        self.cnc_coms_refresh.setGeometry(QtCore.QRect(150, 190, 145, 35))
        self.cnc_coms_refresh.setStyleSheet("QPushButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.cnc_coms_refresh.setObjectName("cnc_coms_refresh")
        self.cnc_connect = QtWidgets.QPushButton(self.pump_coms)
        self.cnc_connect.setGeometry(QtCore.QRect(150, 240, 145, 35))
        self.cnc_connect.setStyleSheet("QPushButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.cnc_connect.setObjectName("cnc_connect")
        self.pump_stacked_widget.addWidget(self.pump_coms)
        self.pump_controls = QtWidgets.QWidget()
        self.pump_controls.setObjectName("pump_controls")
        self.cnc_disc = QtWidgets.QPushButton(self.pump_controls)
        self.cnc_disc.setGeometry(QtCore.QRect(310, 375, 110, 30))
        self.cnc_disc.setStyleSheet("QPushButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.cnc_disc.setObjectName("cnc_disc")
        self.tabWidget = QtWidgets.QTabWidget(self.pump_controls)
        self.tabWidget.setGeometry(QtCore.QRect(70, 50, 301, 271))
        self.tabWidget.setMaximumSize(QtCore.QSize(301, 16777215))
        self.tabWidget.setStyleSheet("/* Entire QTabWidget */\n"
"QTabWidget::pane {\n"
"    background-color: #3B4252; /* Dark background */\n"
"    border: 2px solid #4C566A; /* Single border */\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* Tab Bar (Unselected Tabs) */\n"
"QTabBar::tab {\n"
"    background: #3B4252;\n"
"    color: #D8DEE9;\n"
"    padding: 8px 20px;  /* Same padding for both selected and unselected */\n"
"    border-radius: 8px 8px 0px 0px; /* Only top corners rounded */\n"
"    border: none; /* Removes extra borders */\n"
"    margin-right: 2px;\n"
"    min-width: 100px; /* Ensures consistent width */\n"
"}\n"
"\n"
"/* Selected Tab */\n"
"QTabBar::tab:selected {\n"
"    background: #88C0D0;\n"
"    color: #2E3440;\n"
"    font-weight: bold;\n"
"    padding: 8px 20px; /* Same padding for both selected and unselected */\n"
"    border-bottom: none; /* Removes extra bottom border */\n"
"    min-width: 100px; /* Keeps the width consistent with unselected tabs */\n"
"}\n"
"\n"
"/* Hover Effect */\n"
"QTabBar::tab:hover {\n"
"    background: #5E81AC;\n"
"    color: #ECEFF4;\n"
"}\n"
"\n"
"/* Pressed Effect */\n"
"QTabBar::tab:pressed {\n"
"    background: #81A1C1;\n"
"    color: #2E3440;\n"
"}\n"
"\n"
"/* Content Area */\n"
"QWidget {\n"
"    background-color: #3B4252;\n"
"    border: none; /* Ensures no extra borders */\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.step_size = QtWidgets.QLineEdit(self.tab)
        self.step_size.setGeometry(QtCore.QRect(20, 60, 80, 30))
        self.step_size.setStyleSheet("QLineEdit, QTextEdit {\n"
"    background-color: #3B4252;\n"
"    color: #ECEFF4;\n"
"    border: 1px solid #4C566A;\n"
"    border-radius: 6px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #88C0D0;\n"
"}")
        self.step_size.setAlignment(QtCore.Qt.AlignCenter)
        self.step_size.setPlaceholderText("")
        self.step_size.setObjectName("step_size")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 20, 100, 40))
        self.label.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.cnc_right = QtWidgets.QToolButton(self.tab)
        self.cnc_right.setGeometry(QtCore.QRect(230, 90, 51, 41))
        self.cnc_right.setStyleSheet("/* QToolButton */\n"
"QToolButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    border: 1px solid #4C566A;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #88C0D0;\n"
"    color: #2E3440;\n"
"}")
        self.cnc_right.setArrowType(QtCore.Qt.RightArrow)
        self.cnc_right.setObjectName("cnc_right")
        self.cnc_left = QtWidgets.QToolButton(self.tab)
        self.cnc_left.setEnabled(True)
        self.cnc_left.setGeometry(QtCore.QRect(110, 90, 51, 41))
        self.cnc_left.setStyleSheet("/* QToolButton */\n"
"QToolButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    border: 1px solid #4C566A;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #88C0D0;\n"
"    color: #2E3440;\n"
"}")
        self.cnc_left.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.cnc_left.setArrowType(QtCore.Qt.LeftArrow)
        self.cnc_left.setObjectName("cnc_left")
        self.cnc_up = QtWidgets.QToolButton(self.tab)
        self.cnc_up.setEnabled(True)
        self.cnc_up.setGeometry(QtCore.QRect(170, 40, 51, 41))
        self.cnc_up.setToolTip("")
        self.cnc_up.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cnc_up.setStyleSheet("/* QToolButton */\n"
"QToolButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    border: 1px solid #4C566A;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #88C0D0;\n"
"    color: #2E3440;\n"
"}")
        self.cnc_up.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.cnc_up.setArrowType(QtCore.Qt.UpArrow)
        self.cnc_up.setObjectName("cnc_up")
        self.cnc_down = QtWidgets.QToolButton(self.tab)
        self.cnc_down.setEnabled(True)
        self.cnc_down.setGeometry(QtCore.QRect(170, 140, 51, 41))
        self.cnc_down.setToolTip("")
        self.cnc_down.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cnc_down.setStyleSheet("/* QToolButton */\n"
"QToolButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"    border: 1px solid #4C566A;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: #88C0D0;\n"
"    color: #2E3440;\n"
"}")
        self.cnc_down.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.cnc_down.setArrowType(QtCore.Qt.DownArrow)
        self.cnc_down.setObjectName("cnc_down")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cnc_x_res = QtWidgets.QLineEdit(self.tab_2)
        self.cnc_x_res.setGeometry(QtCore.QRect(110, 40, 80, 30))
        self.cnc_x_res.setStyleSheet("QLineEdit, QTextEdit {\n"
"    background-color: #3B4252;\n"
"    color: #ECEFF4;\n"
"    border: 1px solid #4C566A;\n"
"    border-radius: 6px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #88C0D0;\n"
"}")
        self.cnc_x_res.setAlignment(QtCore.Qt.AlignCenter)
        self.cnc_x_res.setPlaceholderText("")
        self.cnc_x_res.setObjectName("cnc_x_res")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(95, 80, 100, 40))
        self.label_6.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.cnc_x_span = QtWidgets.QLineEdit(self.tab_2)
        self.cnc_x_span.setGeometry(QtCore.QRect(105, 120, 80, 30))
        self.cnc_x_span.setStyleSheet("QLineEdit, QTextEdit {\n"
"    background-color: #3B4252;\n"
"    color: #ECEFF4;\n"
"    border: 1px solid #4C566A;\n"
"    border-radius: 6px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #88C0D0;\n"
"}")
        self.cnc_x_span.setAlignment(QtCore.Qt.AlignCenter)
        self.cnc_x_span.setPlaceholderText("")
        self.cnc_x_span.setObjectName("cnc_x_span")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(95, 0, 100, 40))
        self.label_7.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.cnc_y_span = QtWidgets.QLineEdit(self.tab_2)
        self.cnc_y_span.setGeometry(QtCore.QRect(200, 120, 80, 30))
        self.cnc_y_span.setStyleSheet("QLineEdit, QTextEdit {\n"
"    background-color: #3B4252;\n"
"    color: #ECEFF4;\n"
"    border: 1px solid #4C566A;\n"
"    border-radius: 6px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #88C0D0;\n"
"}")
        self.cnc_y_span.setAlignment(QtCore.Qt.AlignCenter)
        self.cnc_y_span.setPlaceholderText("")
        self.cnc_y_span.setObjectName("cnc_y_span")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(190, 0, 100, 40))
        self.label_8.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(190, 80, 100, 40))
        self.label_9.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.cnc_y_res = QtWidgets.QLineEdit(self.tab_2)
        self.cnc_y_res.setGeometry(QtCore.QRect(200, 40, 80, 30))
        self.cnc_y_res.setStyleSheet("QLineEdit, QTextEdit {\n"
"    background-color: #3B4252;\n"
"    color: #ECEFF4;\n"
"    border: 1px solid #4C566A;\n"
"    border-radius: 6px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #88C0D0;\n"
"}")
        self.cnc_y_res.setAlignment(QtCore.Qt.AlignCenter)
        self.cnc_y_res.setPlaceholderText("")
        self.cnc_y_res.setObjectName("cnc_y_res")
        self.cnc_acquire = QtWidgets.QPushButton(self.tab_2)
        self.cnc_acquire.setGeometry(QtCore.QRect(130, 180, 110, 30))
        self.cnc_acquire.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.cnc_acquire.setObjectName("cnc_acquire")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 100, 71, 51))
        self.label_14.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.cnc_acq_data = QtWidgets.QRadioButton(self.tab_2)
        self.cnc_acq_data.setEnabled(True)
        self.cnc_acq_data.setGeometry(QtCore.QRect(35, 50, 30, 30))
        self.cnc_acq_data.setStyleSheet("/* QRadioButton */\n"
"QRadioButton {\n"
"    color: #D8DEE9;\n"
"    font-size: 14px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #4C566A;\n"
"    background: #3B4252;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background: #88C0D0;\n"
"    border: 2px solid #88C0D0;\n"
"}\n"
"")
        self.cnc_acq_data.setText("")
        self.cnc_acq_data.setObjectName("cnc_acq_data")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(20, 10, 61, 40))
        self.label_15.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(30, 150, 71, 21))
        self.label_17.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(30, 180, 71, 21))
        self.label_19.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.CheckBox_Direction_Y = QtWidgets.QCheckBox(self.tab_2)
        self.CheckBox_Direction_Y.setGeometry(QtCore.QRect(10, 150, 16, 17))
        self.CheckBox_Direction_Y.setText("")
        self.CheckBox_Direction_Y.setObjectName("CheckBox_Direction_Y")
        self.CheckBox_Direction_X = QtWidgets.QCheckBox(self.tab_2)
        self.CheckBox_Direction_X.setGeometry(QtCore.QRect(10, 180, 16, 17))
        self.CheckBox_Direction_X.setText("")
        self.CheckBox_Direction_X.setObjectName("CheckBox_Direction_X")
        self.tabWidget.addTab(self.tab_2, "")
        self.cnc_stop = QtWidgets.QPushButton(self.pump_controls)
        self.cnc_stop.setGeometry(QtCore.QRect(50, 375, 70, 30))
        self.cnc_stop.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.cnc_stop.setObjectName("cnc_stop")
        self.cnc_disc.raise_()
        self.cnc_stop.raise_()
        self.tabWidget.raise_()
        self.pump_stacked_widget.addWidget(self.pump_controls)
        self.board_stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.board_stacked_widget.setGeometry(QtCore.QRect(0, 440, 460, 440))
        self.board_stacked_widget.setStyleSheet("/* QStackedWidget */\n"
"QStackedWidget {\n"
"    background-color: #2E3440;\n"
"    border: 2px solid #4C566A;\n"
"    border-radius: 6px;\n"
"    padding: 5px;\n"
"}")
        self.board_stacked_widget.setFrameShape(QtWidgets.QFrame.Box)
        self.board_stacked_widget.setObjectName("board_stacked_widget")
        self.board_coms = QtWidgets.QWidget()
        self.board_coms.setObjectName("board_coms")
        self.board_coms_refresh = QtWidgets.QPushButton(self.board_coms)
        self.board_coms_refresh.setGeometry(QtCore.QRect(150, 200, 145, 35))
        self.board_coms_refresh.setStyleSheet("QPushButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.board_coms_refresh.setObjectName("board_coms_refresh")
        self.board_coms_list = QtWidgets.QComboBox(self.board_coms)
        self.board_coms_list.setGeometry(QtCore.QRect(150, 140, 145, 35))
        self.board_coms_list.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.board_coms_list.setObjectName("board_coms_list")
        self.board_connect = QtWidgets.QPushButton(self.board_coms)
        self.board_connect.setGeometry(QtCore.QRect(150, 250, 145, 35))
        self.board_connect.setStyleSheet("QPushButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.board_connect.setObjectName("board_connect")
        self.board_stacked_widget.addWidget(self.board_coms)
        self.board_controls = QtWidgets.QWidget()
        self.board_controls.setObjectName("board_controls")
        self.board_disc = QtWidgets.QPushButton(self.board_controls)
        self.board_disc.setGeometry(QtCore.QRect(310, 375, 110, 30))
        self.board_disc.setStyleSheet("QPushButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.board_disc.setObjectName("board_disc")
        self.frame = QtWidgets.QFrame(self.board_controls)
        self.frame.setGeometry(QtCore.QRect(20, 35, 400, 311))
        self.frame.setStyleSheet("/* General Frame Styling */\n"
"QFrame {\n"
"    background-color: #3B4252;  /* Dark background */\n"
"    border: 2px solid #4C566A; /* Subtle border */\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"/* Frame with Sunken Style */\n"
"QFrame[sunken=\"true\"] {\n"
"    border: 2px inset #4C566A;\n"
"}\n"
"\n"
"/* Frame with Raised Style */\n"
"QFrame[raised=\"true\"] {\n"
"    border: 2px outset #4C566A;\n"
"}\n"
"\n"
"/* Styling for a Specific Frame Object (Replace \'myFrame\' with your object name) */\n"
"#myFrame {\n"
"    background-color: #434C5E;\n"
"    border: 2px solid #88C0D0;\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setObjectName("frame")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 100, 40))
        self.label_10.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 100, 40))
        self.label_3.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(180, 20, 100, 40))
        self.label_4.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(180, 60, 100, 40))
        self.label_12.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(10, 100, 100, 40))
        self.label_13.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.board_ch0_read = QtWidgets.QLabel(self.frame)
        self.board_ch0_read.setGeometry(QtCore.QRect(90, 30, 80, 30))
        self.board_ch0_read.setStyleSheet("QLabel {\n"
"    background-color: #3B4252;  /* Dark background to match the input style */\n"
"    color: #ECEFF4;  /* Light text color for readability */\n"
"    border: 1px solid #4C566A;  /* Soft border like input fields */\n"
"    border-radius: 6px;  /* Rounded corners for a consistent look */\n"
"    padding: 4px;  /* Padding around the text for cleaner spacing */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 1px solid #88C0D0;  /* Border color change on hover (optional) */\n"
"}\n"
"\n"
"QLabel:focus {\n"
"    border: 1px solid #88C0D0;  /* Highlighted border when focused (optional) */\n"
"}\n"
"")
        self.board_ch0_read.setText("")
        self.board_ch0_read.setObjectName("board_ch0_read")
        self.board_ch1_read = QtWidgets.QLabel(self.frame)
        self.board_ch1_read.setGeometry(QtCore.QRect(260, 30, 80, 30))
        self.board_ch1_read.setStyleSheet("QLabel {\n"
"    background-color: #3B4252;  /* Dark background to match the input style */\n"
"    color: #ECEFF4;  /* Light text color for readability */\n"
"    border: 1px solid #4C566A;  /* Soft border like input fields */\n"
"    border-radius: 6px;  /* Rounded corners for a consistent look */\n"
"    padding: 4px;  /* Padding around the text for cleaner spacing */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 1px solid #88C0D0;  /* Border color change on hover (optional) */\n"
"}\n"
"\n"
"QLabel:focus {\n"
"    border: 1px solid #88C0D0;  /* Highlighted border when focused (optional) */\n"
"}\n"
"")
        self.board_ch1_read.setText("")
        self.board_ch1_read.setObjectName("board_ch1_read")
        self.board_ch2_read = QtWidgets.QLabel(self.frame)
        self.board_ch2_read.setGeometry(QtCore.QRect(90, 70, 80, 30))
        self.board_ch2_read.setStyleSheet("QLabel {\n"
"    background-color: #3B4252;  /* Dark background to match the input style */\n"
"    color: #ECEFF4;  /* Light text color for readability */\n"
"    border: 1px solid #4C566A;  /* Soft border like input fields */\n"
"    border-radius: 6px;  /* Rounded corners for a consistent look */\n"
"    padding: 4px;  /* Padding around the text for cleaner spacing */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 1px solid #88C0D0;  /* Border color change on hover (optional) */\n"
"}\n"
"\n"
"QLabel:focus {\n"
"    border: 1px solid #88C0D0;  /* Highlighted border when focused (optional) */\n"
"}\n"
"")
        self.board_ch2_read.setText("")
        self.board_ch2_read.setObjectName("board_ch2_read")
        self.board_ch3_read = QtWidgets.QLabel(self.frame)
        self.board_ch3_read.setGeometry(QtCore.QRect(260, 70, 80, 30))
        self.board_ch3_read.setStyleSheet("QLabel {\n"
"    background-color: #3B4252;  /* Dark background to match the input style */\n"
"    color: #ECEFF4;  /* Light text color for readability */\n"
"    border: 1px solid #4C566A;  /* Soft border like input fields */\n"
"    border-radius: 6px;  /* Rounded corners for a consistent look */\n"
"    padding: 4px;  /* Padding around the text for cleaner spacing */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 1px solid #88C0D0;  /* Border color change on hover (optional) */\n"
"}\n"
"\n"
"QLabel:focus {\n"
"    border: 1px solid #88C0D0;  /* Highlighted border when focused (optional) */\n"
"}\n"
"")
        self.board_ch3_read.setText("")
        self.board_ch3_read.setObjectName("board_ch3_read")
        self.board_ch4_read = QtWidgets.QLabel(self.frame)
        self.board_ch4_read.setGeometry(QtCore.QRect(90, 110, 80, 30))
        self.board_ch4_read.setStyleSheet("QLabel {\n"
"    background-color: #3B4252;  /* Dark background to match the input style */\n"
"    color: #ECEFF4;  /* Light text color for readability */\n"
"    border: 1px solid #4C566A;  /* Soft border like input fields */\n"
"    border-radius: 6px;  /* Rounded corners for a consistent look */\n"
"    padding: 4px;  /* Padding around the text for cleaner spacing */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 1px solid #88C0D0;  /* Border color change on hover (optional) */\n"
"}\n"
"\n"
"QLabel:focus {\n"
"    border: 1px solid #88C0D0;  /* Highlighted border when focused (optional) */\n"
"}\n"
"")
        self.board_ch4_read.setText("")
        self.board_ch4_read.setObjectName("board_ch4_read")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(180, 100, 100, 40))
        self.label_18.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setWordWrap(True)
        self.label_18.setObjectName("label_18")
        self.board_ch5_read = QtWidgets.QLabel(self.frame)
        self.board_ch5_read.setGeometry(QtCore.QRect(260, 110, 80, 30))
        self.board_ch5_read.setStyleSheet("QLabel {\n"
"    background-color: #3B4252;  /* Dark background to match the input style */\n"
"    color: #ECEFF4;  /* Light text color for readability */\n"
"    border: 1px solid #4C566A;  /* Soft border like input fields */\n"
"    border-radius: 6px;  /* Rounded corners for a consistent look */\n"
"    padding: 4px;  /* Padding around the text for cleaner spacing */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 1px solid #88C0D0;  /* Border color change on hover (optional) */\n"
"}\n"
"\n"
"QLabel:focus {\n"
"    border: 1px solid #88C0D0;  /* Highlighted border when focused (optional) */\n"
"}\n"
"")
        self.board_ch5_read.setText("")
        self.board_ch5_read.setAlignment(QtCore.Qt.AlignCenter)
        self.board_ch5_read.setObjectName("board_ch5_read")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(180, 260, 100, 40))
        self.label_25.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setWordWrap(True)
        self.label_25.setObjectName("label_25")
        self.board_id_read = QtWidgets.QLabel(self.frame)
        self.board_id_read.setGeometry(QtCore.QRect(260, 270, 80, 30))
        self.board_id_read.setStyleSheet("QLabel {\n"
"    background-color: #3B4252;  /* Dark background to match the input style */\n"
"    color: #ECEFF4;  /* Light text color for readability */\n"
"    border: 1px solid #4C566A;  /* Soft border like input fields */\n"
"    border-radius: 6px;  /* Rounded corners for a consistent look */\n"
"    padding: 4px;  /* Padding around the text for cleaner spacing */\n"
"    text-align: center;\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    border: 1px solid #88C0D0;  /* Border color change on hover (optional) */\n"
"}\n"
"\n"
"QLabel:focus {\n"
"    border: 1px solid #88C0D0;  /* Highlighted border when focused (optional) */\n"
"}\n"
"")
        self.board_id_read.setText("")
        self.board_id_read.setAlignment(QtCore.Qt.AlignCenter)
        self.board_id_read.setObjectName("board_id_read")
        self.board_read_data = QtWidgets.QPushButton(self.frame)
        self.board_read_data.setEnabled(True)
        self.board_read_data.setGeometry(QtCore.QRect(60, 270, 61, 30))
        self.board_read_data.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.board_read_data.setObjectName("board_read_data")
        self.label_11 = QtWidgets.QLabel(self.board_controls)
        self.label_11.setGeometry(QtCore.QRect(150, 5, 141, 30))
        self.label_11.setStyleSheet("QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 12px;\n"
"    border: none;\n"
"}")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.debug_mode = QtWidgets.QPushButton(self.board_controls)
        self.debug_mode.setGeometry(QtCore.QRect(30, 370, 110, 30))
        self.debug_mode.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.debug_mode.setObjectName("debug_mode")
        self.debug_save = QtWidgets.QPushButton(self.board_controls)
        self.debug_save.setGeometry(QtCore.QRect(160, 370, 101, 30))
        self.debug_save.setStyleSheet("QPushButton {\n"
"    background-color: red;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.debug_save.setObjectName("debug_save")
        self.frame.raise_()
        self.board_disc.raise_()
        self.label_11.raise_()
        self.debug_mode.raise_()
        self.debug_save.raise_()
        self.board_stacked_widget.addWidget(self.board_controls)
        self.board_en_output_write_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.board_en_output_write_2.setGeometry(QtCore.QRect(710, 860, 30, 30))
        self.board_en_output_write_2.setStyleSheet("/* QRadioButton */\n"
"QRadioButton {\n"
"    color: #D8DEE9;\n"
"    font-size: 14px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border-radius: 8px;\n"
"    border: 2px solid #4C566A;\n"
"    background: #3B4252;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background: #88C0D0;\n"
"    border: 2px solid #88C0D0;\n"
"}\n"
"")
        self.board_en_output_write_2.setText("")
        self.board_en_output_write_2.setObjectName("board_en_output_write_2")
        self.heatmapStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.heatmapStackedWidget.setGeometry(QtCore.QRect(460, 60, 1000, 1000))
        self.heatmapStackedWidget.setMinimumSize(QtCore.QSize(400, 300))
        self.heatmapStackedWidget.setStyleSheet("/* QStackedWidget */\n"
"QStackedWidget {\n"
"    background-color: #2E3440;\n"
"    border: 2px solid #4C566A;\n"
"    border-radius: 6px;\n"
"    padding: 5px;\n"
"}")
        self.heatmapStackedWidget.setObjectName("heatmapStackedWidget")
        self.heatmapWidget = QtWidgets.QWidget()
        self.heatmapWidget.setObjectName("heatmapWidget")
        self.heatmapStackedWidget.addWidget(self.heatmapWidget)
        self.debugWidget = QtWidgets.QWidget()
        self.debugWidget.setObjectName("debugWidget")
        self.heatmapStackedWidget.addWidget(self.debugWidget)
        self.debugWidget2 = QtWidgets.QWidget()
        self.debugWidget2.setObjectName("debugWidget2")
        self.heatmapStackedWidget.addWidget(self.debugWidget2)
        self.next_page = QtWidgets.QPushButton(self.centralwidget)
        self.next_page.setGeometry(QtCore.QRect(570, 10, 91, 41))
        self.next_page.setStyleSheet("QPushButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.next_page.setObjectName("next_page")
        self.previous_page = QtWidgets.QPushButton(self.centralwidget)
        self.previous_page.setGeometry(QtCore.QRect(470, 10, 91, 41))
        self.previous_page.setStyleSheet("QPushButton {\n"
"    background-color: #4C566A;\n"
"    color: #ECEFF4;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E81AC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #88C0D0;\n"
"}")
        self.previous_page.setObjectName("previous_page")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pump_stacked_widget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.board_stacked_widget.setCurrentIndex(0)
        self.heatmapStackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cnc_coms_refresh.setText(_translate("MainWindow", "Refresh CNC Ports"))
        self.cnc_connect.setText(_translate("MainWindow", "CNC Connect"))
        self.cnc_disc.setText(_translate("MainWindow", "Disconnect"))
        self.step_size.setText(_translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "Step size [mm]"))
        self.cnc_right.setText(_translate("MainWindow", "..."))
        self.cnc_left.setText(_translate("MainWindow", "..."))
        self.cnc_up.setText(_translate("MainWindow", "..."))
        self.cnc_down.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Control"))
        self.cnc_x_res.setText(_translate("MainWindow", "3"))
        self.label_6.setText(_translate("MainWindow", "X Span [mm]"))
        self.cnc_x_span.setText(_translate("MainWindow", "15"))
        self.label_7.setText(_translate("MainWindow", "X Res [mm]"))
        self.cnc_y_span.setText(_translate("MainWindow", "15"))
        self.label_8.setText(_translate("MainWindow", "Y Res [mm]"))
        self.label_9.setText(_translate("MainWindow", "Y Span [mm]"))
        self.cnc_y_res.setText(_translate("MainWindow", "0.1"))
        self.cnc_acquire.setText(_translate("MainWindow", "Start"))
        self.label_14.setText(_translate("MainWindow", "Scan Direction"))
        self.label_15.setText(_translate("MainWindow", "Acquire \n"
"Data"))
        self.label_17.setText(_translate("MainWindow", "Up/Down"))
        self.label_19.setText(_translate("MainWindow", "Right/Left"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sweep"))
        self.cnc_stop.setText(_translate("MainWindow", "STOP \n"
"Pump"))
        self.board_coms_refresh.setText(_translate("MainWindow", "Refresh Board Ports"))
        self.board_connect.setText(_translate("MainWindow", "Board Connect"))
        self.board_disc.setText(_translate("MainWindow", "Disconnect"))
        self.label_10.setText(_translate("MainWindow", "CH2"))
        self.label_3.setText(_translate("MainWindow", "CH0"))
        self.label_4.setText(_translate("MainWindow", "CH1"))
        self.label_12.setText(_translate("MainWindow", "CH3"))
        self.label_13.setText(_translate("MainWindow", "CH4"))
        self.label_18.setText(_translate("MainWindow", "CH5"))
        self.label_25.setText(_translate("MainWindow", "ID"))
        self.board_read_data.setText(_translate("MainWindow", "Read"))
        self.label_11.setText(_translate("MainWindow", "Channel values (aF)"))
        self.debug_mode.setText(_translate("MainWindow", "Debug"))
        self.debug_save.setText(_translate("MainWindow", "Save"))
        self.next_page.setText(_translate("MainWindow", "Odd"))
        self.previous_page.setText(_translate("MainWindow", "Even"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
